# Week 2- Data Structures and Dataframe Operations

**Objectives**: Today we are going to explore both Python-specific and general data structures that are important to data science. We will cover the following:
  
* Variables and datatypes
* Strings, lists, and tuples
* NumPy arrays
* Dictionaries and JSON
* Arrays, dataframes, and series
* Basic dataframe operations

## Variables and Basic Datatypes

Variables in Python are names for values that are stored in memory. Typically, local variables in Python use lower case letters and underscores "_" to create words or statements that describe the value of the variable. More detailed style information can be found in the [PEP 8](https://www.python.org/dev/peps/pep-0008) style guide. Here is a simple example of a variable called "counter":

<code>counter = 2</code>

Unlike other languages, Python uses dynamic typing, so datatypes are inferred from the value of the variable. In the "<code>counter</code>" example above, Python assumes that the "2" is an integer or type of <code>int</code>. 

Knowing that <code>counter</code> is an integer is critical if you plan to do any calculations with it. For example, if you divided the value in <code>counter</code> by 4 and expect the answer to be .5, you would be mistaken. Try this in the code block below:

In [1]:
# Assign 2 to a variable named "counter"
counter = 2

In [4]:
# Call "counter"
type(counter)

int

In [5]:
# Divide "counter" by 4
counter / 4

0

**Basic Built-in Numeric Datatypes**

Python 2.7.x has the following built-in numeric datatypes:

* <code>int</code>: plain integers like 4
* <code>float</code>: floating point numbers like 4.0
* <code>complex</code>: complex numbers like 4j

> Note: Windows by default uses a 32 bit integer value which has a range of (-2147483648 to 2147483647)
> You may need to explictly set the data type to a 64 bit value using the dtype='int64' option in a
> Numpy array like: <code>my_array = np.array([1,10,100,1000,10000,100000], dtype='int64')</code> 
> A 64 bit integer has a range of (-9223372036854775808 to 9223372036854775807).

Given these descriptions of numeric datatypes, why did the previous codeblock not return .5 and how could you change the calculation to get that answer?



In [6]:
# Divide "counter" by 4 to return the decimal value
counter

0.5

To determine the datatype of any object, you can use the <code>type</code> function like:

<code>type(object)</code>

Many analytic tasks use numeric types, so it is good to be familiar with them. Beyond numeric values, many analytic tasks will also include other built-in types like:

**Basic Built-in Boolean and Sequence Datatypes**

Boolean types:
* <code>bool</code>: boolean like True or False

Sequence types:
* <code>str</code>: strings like this sequence of characters: "this is a string"
* <code>list</code>: lists like this list of ints: [1,2,3]
* <code>tuple</code>: tuples like this tuple of ints: (1,2,3)

The descriptions of each of these types is intentionally incomplete (why would you use a list versus a tuple, for example?), so you can learn more details here:

* https://docs.python.org/2/library/stdtypes.html

The inner-workings of each of these types can become complex, but understanding the basics of accessing data is important to a data scientist and there are some common approaches regardless of type.

For a sequence type, there are two direct ways to get parts of those sequences- indexing and slicing:

**Indexing**

Python uses a zero-based index that means the first element will be zero, the second element will be one, and so on.  To access a specific value, you append the index of that value to the sequence like:

<code>my_sequence[0] # The zero in square brackets returns the first or 0th element </code>

**Slicing**

Slices work by extending the idea of an index with an operator that allows you to select a range of index locations in a sequence type. Specifically, you use the colon operator (<code>:</code>) and index locations to retrieve parts of the sequence like:

````
my_sequence[start:end] # items from start through end-1
my_sequence[start:]    # items from start through the rest of the array
my_sequence[:end]      # items from the beginning through end-1
my_sequence[:]         # the whole array
````

Enter some different sequence types below and index and slice them to return their elements.

In [7]:
# Assign a string type sequence with five elements to a variable name
characters = 'abcde'

In [8]:
# Print the variable
characters

'abcde'

In [12]:
# Return the 4th element
characters[3]

'd'

In [10]:
# Return from the 2nd element to the end of the sequence
characters[1:]

'bcde'

In [13]:
# Assign a list type sequence with five elements to a variable name
my_list = [1, 'Sean', True, 0, characters[1:]]

In [14]:
# Print the list
my_list

[1, 'Sean', True, 0, 'bcde']

In [15]:
# Return the 2nd element of the list
my_list[1]

'Sean'

In [23]:
# Return from the 1st element to the end of the sequence
type(my_list)

list

In [19]:
# Assign a tuple type sequence with five elements that are bools to a variable name
my_tuple = (1, 'Sean', True, 0, characters[1:])

In [20]:
# Print the tuple
my_tuple

(1, 'Sean', True, 0, 'bcde')

In [21]:
# Print the 2nd element
my_tuple[1]

'Sean'

In [22]:
# Print from the 2nd element to the end of the sequence
type(my_tuple)

tuple

## NumPy Arrays

The basic variables and sequence types are quite useful for a variety of tasks, but arrays and dataframes are the workhorses of analytics and data science. Arrays and dataframes are great not only because they can represent multidimensional data like a spreadsheet, but also because they use vectorized code. In Python this means both NumPy arrays and the more general and flexible pandas dataframes use optimized C code that doesn't need to use Python for loops and can therefore be much more concise and much faster.

With large datasets, the speedup of vectorized operations can be significant when compared to <code>for</code> loops. When working with dataframes or arrays, try to think in matrix terms rather than iterating through each element.

**Numpy**

Numpy arrays can perform basic mathematics operations like add, subtract, multiply, and divide among arrays with the same shape on an element by element basis as follows.  Observe that this is a truly element by element operation and not matrix multiplication.

In [31]:
import numpy as np

my_arr = np.array([[10,20,30],[100,200,300],[1,2,3]])
print 'this is my_arr:'
print my_arr

this is my_arr:
[[ 10  20  30]
 [100 200 300]
 [  1   2   3]]


In [28]:
my_other_arr = np.array([[1,0,1],[0,1,0],[1,0,1]])
print 'this is my_other_arr:'
print my_other_arr

this is my_other_arr:
[[1 0 1]
 [0 1 0]
 [1 0 1]]


In [29]:
print 'this is the product of my two arrays:' 
print my_arr * my_other_arr

this is the product of my two arrays:
[[[10, 20, 30] [] [1, 2]]
 [[] [100, 200, 300] []]
 [[10, 20, 30] [] [1, 2]]]


When the arrays are different shapes, Numpy can broadcast compatibly shaped arrays together. In the next example, NumPy takes the 3x3 <code>my_arr</code> array and multiplies it by the one-dimensional array <code>my_one_row_arr</code>.

In [ ]:
my_one_row_arr = np.array([[100,0,10]])

print my_arr * my_one_row_arr

Broadcasting essentially replicates the lower dimensional array into the structure of the larger array.  In this case, broadcasting does an element-wise multiplication by multiplying each row of the larger array by each element in the smaller one. 

Try adding an additional element to the 1x3 array to make it a 1x4 and rerun the code multiplying the two arrays. As you will see, broadcasting requires arrays that have compatible sizes.

NumPy mathematical functions are covered here- http://docs.scipy.org/doc/numpy-1.10.0/reference/routines.math.html

**Matrix and Vector Operations**

As you might suspect, NumPy also supports most matrix operataions like multiplication using the <code>numpy.dot(A,B)</code> function. These operations are covered in linear algebra section of the documentation- http://docs.scipy.org/doc/numpy-1.10.0/reference/routines.linalg.html

**Indexing and Slicing Arrays**

Much of the same concepts we covered earlier work in a similar way for NumPy arrays except using multiple dimensions. To access a given element in a 2 dimensional array the same basic Python syntax applies as in <code>x[obj]</code>. Instead of a single value index as in the sequence, you can either return a row with a scalar value or an element within a row by selecting <code>[row,row_index]</code>.  

Try accessing rows and individual elements in my array below.

In [32]:
my_arr[0,0]

10

Slicing also works in a similar way by using the ellipsis. Try the following slices below.

In [33]:
# Slice to return the last two rows

my_arr[1:,]

array([[100, 200, 300],
       [  1,   2,   3]])

In [34]:
# Slice to return the 2nd column

my_arr[:,1]

array([ 20, 200,   2])

**Boolean Masks**

Boolean masks are a critical component of many analyses given they are simple, vectorized approaches to filtering and constructing new arrays for a topic of interest. Masks are conceptually simple. Run the code below to see what happens when we add a boolean test to our array. The syntax is the same as the earlier basic arithmetic operations that are broadcast across the array. 

In [37]:
my_arr >= 20

array([[False,  True,  True],
       [ True,  True,  True],
       [False, False, False]], dtype=bool)

The resulting array is the same shape, but has boolean values for the element-wise logical test. You can see this in the <code>dtype=bool</code> output.

Where this gets really cool is when we combine this result with our selection syntax.  Before you run the next cell, what do you think the results will be?

In [38]:
my_arr[my_arr > 20]

array([ 30, 100, 200, 300])

The result should be a one-dimensional array of the element-wise logical test.

If you want to learn more about indexing in NumPy try these resources:

* http://docs.scipy.org/doc/numpy/reference/arrays.indexing.html

## Dictionaries and JSON

**Dictionaries**

Dictionaries are another important data type in Python. Dictionaries contain elements like sequences, but instead of referencing items by position, they use names. In the simplest terms, a dictionary is a collection of key-value pairs like:

````
{"user_number":123,
"user_name":"Issac"}
````

Where lists use <code>[]</code> and tuples use <code>()</code>, dictionaries or dicts use <code>{}</code>. To build a dictionary, within the curly brackets, keys precede their values with a colon like

````
{'my key':126}
````

Dictionaries are unordered, so the only way to retrieve a specific value for a given key is via its name.  Dictionaries also have to have unique keys, but values need not be unique. Run the code below to demonstrate.

In [40]:
my_dict = {'user_number':123,
           'user_name':'Issac'}

my_dict['user_number']

123

While we have only been dealing with sequences and dictionaries with one level, all of these structures can support nested elements of multiple types. Try the following to explore this ability. Try some different datatypes in the value and key positions.

In [41]:
# Build a dictionary with two keys (odds and evens) and two values 
# that are lists of the odd and even numbers on a single six-sided die 
# and assign it to name "dice".
dice = {
    'odds': [1, 3, 5],
    'evens': [2, 4, 6]
}

In [42]:
# Print the dictionary
dice

{'evens': [2, 4, 6], 'odds': [1, 3, 5]}

In [45]:
# Print the second element of 'evens'
dice['evens'][1]

4

In [46]:
# Print the first element of 'odds'
dice['odds'][0]

1

**JSON and Structured, Semi-Structures, and Unstructured Data**

According to http://json.org:

>JSON (JavaScript Object Notation) is a lightweight data-interchange format. It is easy for humans to read and write. It is easy for machines to parse and generate. It is based on a subset of the JavaScript Programming Language, Standard ECMA-262 3rd Edition - December 1999. JSON is a text format that is completely language independent but uses conventions that are familiar to programmers of the C-family of languages, including C, C++, C#, Java, JavaScript, Perl, Python, and many others. These properties make JSON an ideal data-interchange language.
>
>JSON is built on two structures:
>
>* A collection of name/value pairs. In various languages, this is realized as an object, record, struct, dictionary, hash table, keyed list, or associative array.
>
>* An ordered list of values. In most languages, this is realized as an array, vector, list, or sequence.


For those interested in data science and analytics, JSON is a very common datatype. Many new NoSQL databases use JSON or JSON-like models as their foundational data structure or offer features to handle JSON documents like:

* mongoDB- https://docs.mongodb.org/manual/core/data-modeling-introduction/
* DynamoDB- https://aws.amazon.com/blogs/aws/dynamodb-update-json-and-more/
* Spark SQL- https://databricks.com/blog/2015/02/02/an-introduction-to-json-support-in-spark-sql.html

An example JSON message from http://json.org/example.html follows.

````
{
    "glossary": {
        "title": "example glossary",
		"GlossDiv": {
            "title": "S",
			"GlossList": {
                "GlossEntry": {
                    "ID": "SGML",
					"SortAs": "SGML",
					"GlossTerm": "Standard Generalized Markup Language",
					"Acronym": "SGML",
					"Abbrev": "ISO 8879:1986",
					"GlossDef": {
                        "para": "A meta-markup language, used to create markup languages such as DocBook.",
						"GlossSeeAlso": ["GML", "XML"]
                    },
					"GlossSee": "markup"
                }
            }
        }
    }
}
````


If you are working with data generated from the web, odds are that that data will follow the JSON format. Even the file format of this Jupyter notebook is JSON. 

When talking in data science circles, JSON would be considered semi-structured data within this spectrum of structuredness:

* **Structured**: Structured data is typically referring to the well-defined schemas of relational databases where there are predefined rows and columns or tables.

* **Semi-Structured**: Semi-structured data has some organization for its elements, but does not dictate a defined structure as in a relational database's table. Data can be retrieved from semi-structured data using a key or label as in the Python dictionary. Other examples of semi-structured data include JSON and CSV.

* **Unstructured**: Unstructured data lacks any predefined schema or model. Examples of unstructured data might include audio files or unlabeled text scrapped from the web.


**JSON in Python**

Conceptually, JSON is quite similar to Python's dictionary. In practice, however, JSON requires specific formatting to be valid and therefore interoperate with other systems. The Python JSON library makes it quite easy to both encode and decode to and from JSON and native Python datatypes. 

For encoding, <code>json.dumps(object)</code> is the primary method as can be seen below.

In [47]:
import json

python_dict = {'class':'big data', 'favorite technologies':['Python', 'Spark', 'AWS', 'Jupyter', 'Google BigQuery']}


# Convert it to JSON
json.dumps(python_dict)

'{"class": "big data", "favorite technologies": ["Python", "Spark", "AWS", "Jupyter", "Google BigQuery"]}'

Look at the output of <code>json.dumps</code>.  How is it different from the dictionary object?  What is the return type of <code>json.dumps</code>?

> A quick aside: to determine a type of any object empirically, use <code>type(object)</code>


The json library predictably helps you read JSON into native Python datatypes too. Read our sample file below and then determine the type of the resulting object.

In [48]:
with open('./datasets/sample.json') as json_file:
    data = json.load(json_file)

In [49]:
# What type is "data"
type(data)

list

Now, print the contents of the file. For formatting, we will use the "pretty print" library to make the output nicer in our notebook- https://docs.python.org/2/library/pprint.html.

In [52]:
from pprint import pprint

pprint(data)

[{u'_id': u'564673125069f35219dd872e',
  u'about': u'Eu reprehenderit consectetur est elit adipisicing. Laboris deserunt est sint labore fugiat veniam cupidatat quis. Lorem voluptate consequat exercitation velit officia duis ad deserunt ea enim cupidatat deserunt amet.\r\n',
  u'address': u'532 Beadel Street, Grimsley, Indiana, 9043',
  u'age': 25,
  u'balance': u'$3,133.96',
  u'company': u'ATOMICA',
  u'email': u'dorispearson@atomica.com',
  u'eyeColor': u'brown',
  u'favoriteFruit': u'apple',
  u'friends': [{u'id': 0, u'name': u'Lott Hahn'},
               {u'id': 1, u'name': u'Ruth Berg'},
               {u'id': 2, u'name': u'Conway Bryan'}],
  u'gender': u'female',
  u'greeting': u'Hello, Doris Pearson! You have 6 unread messages.',
  u'guid': u'4dd19428-c8e9-4abe-8061-59ea3e3eddcc',
  u'index': 0,
  u'isActive': True,
  u'latitude': -82.139093,
  u'longitude': -11.271248,
  u'name': u'Doris Pearson',
  u'phone': u'+1 (890) 567-3994',
  u'picture': u'http://placehold.it/32x32',
  

Using the same general approach to selecting data, assign the "company" field from the first element of the <code>data</code> object to a variable in the next cell.

In [53]:
# What is the company name of the first element in data
data[0]['company']

u'ATOMICA'

## pandas Series and Dataframes

We used a pandas dataframe in the last exercise, so let's explore data selection, filtering, and some of the built-in statistics functions in more detail for it and the one-dimensional pandas series.

**Indexing a Series**

Indexing a series uses the hopefully familiar <code>series[label]</code> format. A "label" for a series can either be the zero-index position or the label of the index. Try the following.

In [54]:
import pandas as pd
import math

# Make a series
my_series = pd.Series([42,'towel',math.pi], index=['one','two','three'])

In [55]:
# Print the series
my_series

one            42
two         towel
three    3.141593
dtype: object

In [56]:
# Return the 2nd element of the series by location
my_series[1]

'towel'

In [57]:
# Return the element called "three" by name
my_series['three']

3.141592653589793

In [58]:
# What is the datatype of the "three" element
type(my_series['three'])

float

**Boolean Masks**

pandas masks are similar to those in NumPy of form

```
series[series logical test]
dataframe[dataframe logical test]
```
like
```
df[df['column_name']=='criteria']
```

where the inner term returns a boolean mask to then derive the relevant elements from the outer series object.

Try this below by first creating a logical test to return the boolean mask of items that are "towel" in <code>my_series</code>.  Refer to the Python logical operators listed under comparisons at 

* https://docs.python.org/2/library/stdtypes.html 

and the pandas documentation on boolean indexing at 

* http://pandas.pydata.org/pandas-docs/stable/indexing.html#boolean-indexing

In [88]:
# First, print a boolean vector of all the elements that are "towel"
my_series == 'towel'

one      False
two       True
three    False
dtype: bool

In [89]:
# Now pass the vector to the series to return any elements that are True
my_series[my_series == 'towel']

two    towel
dtype: object

In [90]:
# Now create a boolean mask that returns all elements from my_series that are "towel" or 42
my_series[(my_series == 'towel') | (my_series == 42)]

one       42
two    towel
dtype: object

**Indexing a Dataframe**

There are several different methods to index a dataframe. Given most dataframes are multidimensional and can include named labels both for the row index and column names, the syntax requires more methods.  The primary selection methods are: 

* <code>df.ix</code> is the most general index method as it supports both label and location based indexing. 
* <code>df.loc</code> is primarily label based using the names of rows or columns.
* <code>df.iloc</code> is primarily location based again using zero-based integers to index.

All methods use this syntax to select rows and columns and follow the same conventions as the previous objects:

<code>df.ix[row_indexer,column_indexer]</code>

More details on indexing and data selection can be found here:

http://pandas.pydata.org/pandas-docs/stable/indexing.html

Try the examples below.

In [71]:
# We will use NumPy's randn function which returns random samples 
# from a normal distribution. This function returns a matrix of the 
# size specified as attributes which, in this case, is 4x4.

df_data = np.random.randn(4,4)

# Now, we will call the NumPy array to see its elements

df_data

array([[ 0.23696402, -0.95357449,  1.73416832, -1.99027324],
       [ 0.83747103, -0.331586  , -0.81819792, -0.45994345],
       [-0.5790761 , -0.42328115, -0.00677315, -1.43529826],
       [ 1.51351359,  0.16794852, -1.00171899, -0.28041493]])

In [72]:
# Let's use the data to build a dataframe without any labels

df = pd.DataFrame(data=df_data)

# Let's call the dataframe

df

0         1         2         3
0  0.236964 -0.953574  1.734168 -1.990273
1  0.837471 -0.331586 -0.818198 -0.459943
2 -0.579076 -0.423281 -0.006773 -1.435298
3  1.513514  0.167949 -1.001719 -0.280415

Notice in the output above, the dataframe filled in integer values for rows and columns as neither was specified when the dataframe was created. Try to retrieve elements of the dataframe below.

In [73]:
# Select the first column of the df. Notice that the result should be a panads series.
# Append the correct code to the print df statements. Using print retains the output.

df.ix[:,0] #<-Your code here.

0    0.236964
1    0.837471
2   -0.579076
3    1.513514
Name: 0, dtype: float64

In [74]:
# Select the third element of the first column

df.ix[2,0] #<-Your code here.

-0.57907609794398129

In [76]:
# Select the first row of the df.

df.ix[0] #<-Your code here.

0    0.236964
1   -0.953574
2    1.734168
3   -1.990273
Name: 0, dtype: float64

Now, let's add some column names to the dataframe.

In [77]:
# Create a list of names, assign to dataframe, and call.

col_names = ['fire', 'water', 'wind', 'earth']
df.columns = col_names # Note this can be specified as an attribute during creation.
df

fire     water      wind     earth
0  0.236964 -0.953574  1.734168 -1.990273
1  0.837471 -0.331586 -0.818198 -0.459943
2 -0.579076 -0.423281 -0.006773 -1.435298
3  1.513514  0.167949 -1.001719 -0.280415

Now, do the following.

In [79]:
# Return the first column of the dataframe using the label.

df.ix[:,'fire']

0    0.236964
1    0.837471
2   -0.579076
3    1.513514
Name: fire, dtype: float64

In [81]:
# Return the second element of the water column by label.

df['water']

0   -0.953574
1   -0.331586
2   -0.423281
3    0.167949
Name: water, dtype: float64

Now, let's create a row index of names.

In [82]:
# Create a list of row names, assign to dataframe index, and call it.

col_rows = ['Sakura', 'Kakashi', 'Shikamaru', 'Rock']
df.index = col_rows # Note this can be specified as an attribute during creation.
df

fire     water      wind     earth
Sakura     0.236964 -0.953574  1.734168 -1.990273
Kakashi    0.837471 -0.331586 -0.818198 -0.459943
Shikamaru -0.579076 -0.423281 -0.006773 -1.435298
Rock       1.513514  0.167949 -1.001719 -0.280415

Apply your indexing and selection skills.

In [84]:
# Return the second row of the dataframe using the label.

df.ix['Kakashi']

fire     0.837471
water   -0.331586
wind    -0.818198
earth   -0.459943
Name: Kakashi, dtype: float64

In [87]:
# Assign the earth value for Sakura to a var and print.

sakura_earth = df.ix['Sakura', 'earth']
print 'Sakura\'s earth value is {}'.format(sakura_earth)

Sakura's earth value is -1.9902732448


**Len: one of the most used methods**

To determine the length of many objects including things like the number of elements in a column of a dataframe, you can use the <code>len</code> method. The syntax is simply: <code>len(obj)</code>

In [86]:
# Find the length of the fire column
len('fire')

4